export const data = [
  { id: 1, name: "Smartphones" },
  { id: 2, name: "Men Sneakers" },
  { id: 3, name: "Headphones" },
  { id: 4, name: "Men Jeans" },
  { id: 5, name: "Stand Mixers" },
  { id: 6, name: "Lipsticks" },
  { id: 7, name: "Action Cameras" },
  { id: 8, name: "Smartwatches" },
  { id: 9, name: "Tablets" },
  { id: 10, name: "Women Athletic Shoes" },
  { id: 11, name: "Drones" },
  { id: 12, name: "Pressure Cookers" },
  { id: 13, name: "Charm Bracelets" },
  { id: 14, name: "Wireless Speakers" },
  { id: 15, name: "Women Leggings" },
  { id: 16, name: "Wireless Earbuds" },
  { id: 18, name: "Mirrorless Cameras" },
  { id: 19, name: "Laptops" },
  { id: 20, name: "VR Headsets" },
  { id: 21, name: "Over-Ear Headphones" },
  { id: 22, name: "DSLR Cameras" },
  { id: 24, name: "Smart Home Hubs" },
  { id: 26, name: "Gaming Laptops" },
  { id: 27, name: "True Wireless Earbuds" },
  { id: 28, name: "Vacuum Cleaners" },
  { id: 29, name: "OLED TVs" },
  { id: 30, name: "Bluetooth Speakers" },
  { id: 32, name: "Smart Speakers" },
  { id: 37, name: "Fitness Trackers" },
  { id: 38, name: "Sunglasses" },
  { id: 39, name: "Cutting Machines" },
  { id: 41, name: "Pressure induction" },
  { id: 42, name: "Men T-Shirts" },
  { id: 43, name: "Gaming Consoles" },
  { id: 44, name: "Women Dresses" },
  { id: 45, name: "Bluetooth Earbuds" },
  { id: 46, name: "Men Watches" },
  { id: 47, name: "Instant Cameras" },
  { id: 48, name: "Women Sandals" },
  { id: 49, name: "E-Readers" },
  { id: 50, name: "Smart Home Cameras" },
  { id: 51, name: "Men Wallets" },
  { id: 52, name: "Women Makeup Palettes" },
  { id: 53, name: "Coffee Makers" },
  { id: 54, name: "Men Belts" },
  { id: 55, name: "Women Handbags" },
  { id: 57, name: "Gaming Headsets" },
  { id: 58, name: "Women Perfumes" },
  { id: 59, name: "Air Fryers" },
  { id: 60, name: "Men Dress Shirts" },
  { id: 62, name: "Women Jewelry Sets" },
  { id: 63, name: "Blenders" },
  { id: 64, name: "Men Shorts" },
  { id: 65, name: "Women Swimwear" },
  { id: 66, name: "Noise-Cancelling Headphones" },
  { id: 67, name: "Projectors" },
  { id: 68, name: "Women Activewear" },
  { id: 69, name: "Robotic Vacuums" },
  { id: 70, name: "Men Suits" },
  { id: 71, name: "Smart Scales" },
  { id: 72, name: "Women Hair Styling Tools" },
  { id: 73, name: "Air Purifiers" },
  { id: 74, name: "Men Backpacks" },
  { id: 75, name: "Women Lingerie" },
  { id: 78, name: "Women Skincare Products" },
  { id: 79, name: "Espresso Machines" },
  { id: 80, name: "Men Hats" },
  { id: 81, name: "Women Scarves" },
  { id: 83, name: "Gaming Chairs" },
  { id: 84, name: "Women Hair Accessories" },
  { id: 85, name: "Slow Cookers" },
  { id: 86, name: "Men Socks" },
  { id: 87, name: "Women Sunglasses" },
  { id: 88, name: "Noise-Cancelling Earbuds" },
  { id: 90, name: "Women Sleepwear" },
  { id: 92, name: "Men Underwear" },
  { id: 93, name: "Women Boots" },
  { id: 95, name: "Men Jackets" },
  { id: 96, name: "Women Jewelry Boxes" },
  { id: 97, name: "Streaming Devices" },
  { id: 98, name: "Men Sweatshirts" },
  { id: 99, name: "Women Hair Dyes" },
  { id: 100, name: "Fitness Strip" },
];
